### ISSUE TITLE
Game Needs Emacs-Style Keybinds

### ISSUE THREAD

**Issue by LWSS** [truncator/gx#1]
Hello this game needs Emacs style keybinds and also needs to be licensed under the GNU GPL V3

I recommend something along the lines of:
- Select all units ( Ctrl+Meta+a )
- Attack move ( Ctrl+a, Meta+v )
- Close game ( Ctrl+x, Ctrl+c )
- In game console ( Meta+x )
  etc...

Thanks

**Comment by truncator** [comment]
good meme

**Comment by LWSS** [comment]
Closed?!?!

**Comment by truncator** [comment]
Locked. :^)
